#!/usr/bin/env python3
# -*- coding: utf-8 -*-

ERR_SUCCESS = 0
ERR_PARAM_VALIDATION = 100
ERR_DEPENDENCY_CHECK = 101
ERR_REDIS_CONNECTION = 102
ERR_REDIS_INFO = 103
ERR_TIMEOUT = 110

ERR_MSG_UNKNOWN = "未知错误"
ERR_MSG_SUCCESS = "执行成功"
ERR_MSG_PARAM_VALIDATION = "参数验证失败"
ERR_MSG_DEPENDENCY_CHECK = "依赖检查失败"
ERR_MSG_REDIS_CONNECTION = "Redis连接失败"
ERR_MSG_REDIS_INFO = "获取Redis信息失败"
ERR_MSG_TIMEOUT = "超时退出"

ERROR_MESSAGES = {
    ERR_SUCCESS: ERR_MSG_SUCCESS,
    ERR_PARAM_VALIDATION: ERR_MSG_PARAM_VALIDATION,
    ERR_DEPENDENCY_CHECK: ERR_MSG_DEPENDENCY_CHECK,
    ERR_REDIS_CONNECTION: ERR_MSG_REDIS_CONNECTION,
    ERR_REDIS_INFO: ERR_MSG_REDIS_INFO,
    ERR_TIMEOUT: ERR_MSG_TIMEOUT
}

def get_error_message(error_code):
    return ERROR_MESSAGES.get(error_code, ERR_MSG_UNKNOWN)
